binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
fn_single_line = true
force_multiline_blocks = false
format_macro_matchers = true
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
match_block_trailing_comma = true
match_arm_blocks = true
max_width = 100
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = false
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = false
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
